### 共通の設定を定義 ###
spring:
  # デフォルトは開発環境の設定値を使う
  profiles:
    default: development
    active: development

  security:
    oauth2:
      client:
        provider:
          #Mocklabのエンドポイント設定
          mocklab:
            user-name-attribute: sub
            authorization-uri: https://azkz.mocklab.io/oauth/authorize
            token-uri: https://azkz.mocklab.io/oauth/token
            user-info-uri: https://azkz.mocklab.io/userinfo
            jwk-set-uri: https://azkz.mocklab.io/.well-known/jwks.json

        #Oauthクライアントの設定
        registration:
          google:
            clientId: ${GOOGLE_OAUTH2_ID:XXX}
            clientSecret: ${GOOGLE_OAUTH2_SECRET:XXX}
          mock-oidc:
            provider: mocklab
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            clientId: mocklab_oidc
            clientSecret: whatever

  # HTTPS対応
  # これがないとログイン時にHTTPになってしまう
  server:
    forward-headers-strategy: native

#余計な情報をユーザーに見られないようにする
endpoints:
  enabled: false
management:
  add-application-context-header: false