spring:
  security:
    #OAuthプロバイダー設定
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH2_ID:XXX}
            clientSecret: ${GOOGLE_OAUTH2_SECRET:XXX}

  #DB設定(接続情報はOS環境変数を参照)
  jpa:
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://${KASHITE_DB_HOST:localhost}:${KASHITE_DB_PORT:5432}/kashite?currentSchema=kashite
    username: ${KASHITE_DB_USER:username}
    password: ${KASHITE_DB_PASSWORD:password}

  # HTTPS対応
  # これがないとログイン時にHTTPになってしまう
  server:
    forward-headers-strategy: native

#余計な情報をユーザーに見られないようにする
endpoints:
  enabled: false
management:
  add-application-context-header: false